export default {
  AppName: 'Talky',
  SignInMsg: 'Sign in to your account',
  DontHaveAcc: "Don't have any account ?",
  Create: 'Create',
  CreateAccount: 'Create Account',
  Users: 'Users',
  Friends: 'Friends',
  Blocked: 'Blocked',
  AreYouSure: 'Are you sure?',
  No: 'No',
  Yes: 'Yes',
  Msgs: 'Messages',
  Email: 'Email',
  Password: 'Password',
  SignIn: 'Sign In',
  YourAcc: 'Your Account',
  Notifications: 'Notifications',
  TermsAndConditions: 'Terms and Conditions',
  HelpAndSupport: 'Help and Support',
  LogOut: 'Log Out',
  Profile: 'Profile',
  ConfirmPassword: 'Confirm Password',
  PhoneNumber: 'Phone Number',
  EmailAddress: 'Email Address',
  YourName: 'Your Name',
  IntroText1: 'Connecting you with the world, one chat at a time.',
  IntroText2: 'Discover a world of possibilities with our chat app ',
  IntroText3:
    'Our app keeps you connected with friends and loved ones, no matter where you are.',
  IntroTitle1: 'Welcome to Talky',
  IntroTitle2: 'Real-time Messaging',
  IntroTitle3: 'Stay Connected, Anytime, Anywhere',
  Skip: 'Skip',
  Next: 'Next',
  Done: 'Done',
  EmaildoesntExist: "email doesn't exist",
  PasswordDoesntMatch: 'Password doesnt match',
  EnterName: 'Please enter name',
  MoreThan3Char: 'Name must have more than 3 char',
  EnterEmail: 'Please fill email',
  ValidEmail: 'Please enter a valid email',
  FillNumber: 'Please fill number',
  Num10Digits: 'Number must have 10 digits',
  FillPassword: 'Please fill password',
  StrongPassword: 'Please create a strong password',
  PasswordDoesntMatch: 'Confirm password doesnt match with password',
  EmailAlreadyReg: 'Email already registered ',
  CreatedSuccesfully: 'Account created succesfully',
  Home: 'Home',
  Search: 'Search',
  EnterText: 'Please enter text',
};

// export default {
//   AppName: 'a',
//   SignInMsg: 'b',
//   DontHaveAcc: 'c',
//   Create: 'd',
//   CreateAccount: 'e',
//   Users: 'f',
//   Friends: 'g',
//   Blocked: 'h',
//   AreYouSure: 'i',
//   No: 'j',
//   Yes: 'k',
//   Msgs: 'l',
//   Email: 'm',
//   Password: 'n',
//   SignIn: 'o',
//   YourAcc: 'p',
//   Notifications: 'q',
//   TermsAndConditions: 'r',
//   HelpAndSupport: 's',
//   LogOut: 't',
//   Profile: 'u',
//   ConfirmPassword: 'v',
//   PhoneNumber: 'w',
//   EmailAddress: 'x',
//   YourName: 'y',
//   IntroText1: 'z',
//   IntroText2: 'aa',
//   IntroText3: 'ab',
//   IntroTitle1: 'ac',
//   IntroTitle2: 'ad',
//   IntroTitle3: 'ae',
//   Skip: 'af',
//   Next: 'ag',
//   Done: 'ah',
//   EmaildoesntExist: 'ai',
//   PasswordDoesntMatch: 'aj',
//   EnterName: 'ak',
//   MoreThan3Char: 'al',
//   EnterEmail: 'am',
//   ValidEmail: 'an',
//   FillNumber: 'ao',
//   Num10Digits: 'ap',
//   FillPassword: 'aq',
//   StrongPassword: 'ar',
//   PasswordDoesntMatch: 'as',
//   EmailAlreadyReg: 'at ',
//   CreatedSuccesfully: 'au',
//   Home: '2',
//   Search: 'a',
// };
